### Get all items.
GET http://localhost:8080/api/v1/todo/


### Create todo item.
POST http://localhost:8080/api/v1/todo
Content-Type: application/json

{
  "text": "Something I need to do."
}


### Get an item.
GET http://localhost:8080/api/v1/todo/uuid


### Update status of todo item.
PATCH http://localhost:8080/api/v1/todo/uuid
Content-Type: application/json

{
  "done": true
}


### Delete an item.
DELETE http://localhost:8080/api/v1/todo/uuid
